version: "3.9"
services:

  spring-api-image:
    image: spring-employees-test-image
    container_name: spring-employees-test-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: pQnfn8FJBRmOGEw
      MYSQL_DATABASE: employees-technical-test-db
      MYSQL_USER: riquelmip
      MYSQL_PASSWORD: 9101
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: